// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using P0002_MyGrid.DataAccess;

#nullable disable

namespace P0002_MyGrid.Migrations
{
    [DbContext(typeof(MyGridContext))]
    partial class MyGridContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("P0002_MyGrid.Model.Grid", b =>
                {
                    b.Property<string>("ItemCode")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("item_code");

                    b.Property<int>("GridNo")
                        .HasColumnType("integer")
                        .HasColumnName("grid_no");

                    b.Property<decimal>("BuyPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("buy_price");

                    b.Property<int>("Hold")
                        .HasColumnType("integer")
                        .HasColumnName("hold");

                    b.Property<decimal>("SellPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("sell_price");

                    b.HasKey("ItemCode", "GridNo");

                    b.ToTable("grid", "my_grid");
                });

            modelBuilder.Entity("P0002_MyGrid.Model.GridTransaction", b =>
                {
                    b.Property<long>("TransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("transaction_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TransactionID"));

                    b.Property<int>("GridNo")
                        .HasColumnType("integer")
                        .HasColumnName("grid_no");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("item_code");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("transaction_date");

                    b.Property<decimal>("TransactionPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("transaction_price");

                    b.Property<int>("TransactionQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("transaction_quantity");

                    b.HasKey("TransactionID");

                    b.ToTable("grid_transaction", "my_grid");
                });
#pragma warning restore 612, 618
        }
    }
}
