// <auto-generated />
using A0006_EF_Sqlite_V6.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace A0006_EF_Sqlite_V6.Migrations
{
    [DbContext(typeof(TestContext))]
    [Migration("20211209060759_MyFirstMigration")]
    partial class MyFirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("A0006_EF_Sqlite_V6.Model.Document", b =>
                {
                    b.Property<long>("DocumentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("document_id");

                    b.Property<string>("DocumentContent")
                        .HasColumnType("TEXT")
                        .HasColumnName("document_content");

                    b.Property<string>("DocumentTitle")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("document_title");

                    b.Property<string>("DocumentTypeCode")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("document_type_code");

                    b.HasKey("DocumentID");

                    b.HasIndex("DocumentTypeCode");

                    b.ToTable("document");
                });

            modelBuilder.Entity("A0006_EF_Sqlite_V6.Model.DocumentType", b =>
                {
                    b.Property<string>("DocumentTypeCode")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("document_type_code");

                    b.Property<string>("DocumentTypeName")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("document_type_name");

                    b.HasKey("DocumentTypeCode");

                    b.ToTable("document_type");
                });

            modelBuilder.Entity("A0006_EF_Sqlite_V6.Model.MrRole", b =>
                {
                    b.Property<string>("RoleCode")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("role_code");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("role_name");

                    b.HasKey("RoleCode");

                    b.ToTable("mr_role");
                });

            modelBuilder.Entity("A0006_EF_Sqlite_V6.Model.MrUser", b =>
                {
                    b.Property<string>("UserCode")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_code");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_name");

                    b.HasKey("UserCode");

                    b.ToTable("mr_user");
                });

            modelBuilder.Entity("A0006_EF_Sqlite_V6.Model.MrUserRole", b =>
                {
                    b.Property<string>("UserCode")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("user_code");

                    b.Property<string>("RoleCode")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("role_code");

                    b.HasKey("UserCode", "RoleCode");

                    b.HasIndex("RoleCode");

                    b.ToTable("mr_user_role");
                });

            modelBuilder.Entity("A0006_EF_Sqlite_V6.Model.TestData", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("address");

                    b.Property<string>("Name")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("phone");

                    b.HasKey("ID");

                    b.ToTable("test_data");
                });

            modelBuilder.Entity("A0006_EF_Sqlite_V6.Model.Document", b =>
                {
                    b.HasOne("A0006_EF_Sqlite_V6.Model.DocumentType", "DocumentType")
                        .WithMany("DocumentList")
                        .HasForeignKey("DocumentTypeCode");

                    b.Navigation("DocumentType");
                });

            modelBuilder.Entity("A0006_EF_Sqlite_V6.Model.MrUserRole", b =>
                {
                    b.HasOne("A0006_EF_Sqlite_V6.Model.MrRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("A0006_EF_Sqlite_V6.Model.MrUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("A0006_EF_Sqlite_V6.Model.DocumentType", b =>
                {
                    b.Navigation("DocumentList");
                });

            modelBuilder.Entity("A0006_EF_Sqlite_V6.Model.MrRole", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("A0006_EF_Sqlite_V6.Model.MrUser", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
