// <auto-generated />
using System;
using System.Collections.Generic;
using A0009_EF_Postgres_V8.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace A0009_EF_Postgres_V8.Migrations
{
    [DbContext(typeof(TestContext))]
    [Migration("20241230030436_MyA0009_EF_Postgres_V8_Add_jsonb")]
    partial class MyA0009_EF_Postgres_V8_Add_jsonb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("A0009_EF_Postgres_V8.Model.Document", b =>
                {
                    b.Property<long>("DocumentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("document_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("DocumentID"));

                    b.Property<string>("DocumentContent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("document_content");

                    b.Property<string>("DocumentTitle")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("document_title");

                    b.Property<string>("DocumentTypeCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("document_type_code");

                    b.HasKey("DocumentID");

                    b.HasIndex("DocumentTypeCode");

                    b.ToTable("document");
                });

            modelBuilder.Entity("A0009_EF_Postgres_V8.Model.DocumentType", b =>
                {
                    b.Property<string>("DocumentTypeCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("document_type_code");

                    b.Property<string>("DocumentTypeName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("document_type_name");

                    b.HasKey("DocumentTypeCode");

                    b.ToTable("document_type");
                });

            modelBuilder.Entity("A0009_EF_Postgres_V8.Model.MrRole", b =>
                {
                    b.Property<string>("RoleCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role_code");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("role_name");

                    b.HasKey("RoleCode");

                    b.ToTable("mr_role");
                });

            modelBuilder.Entity("A0009_EF_Postgres_V8.Model.MrUser", b =>
                {
                    b.Property<string>("UserCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("user_code");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("user_name");

                    b.HasKey("UserCode");

                    b.ToTable("mr_user");
                });

            modelBuilder.Entity("A0009_EF_Postgres_V8.Model.MrUserExp", b =>
                {
                    b.Property<string>("UserCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("user_code");

                    b.Property<string>("UserExpData")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("user_exp_data");

                    b.HasKey("UserCode");

                    b.ToTable("mr_user_exp");
                });

            modelBuilder.Entity("A0009_EF_Postgres_V8.Model.MrUserRole", b =>
                {
                    b.Property<string>("UserCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("user_code");

                    b.Property<string>("RoleCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("role_code");

                    b.HasKey("UserCode", "RoleCode");

                    b.HasIndex("RoleCode");

                    b.ToTable("mr_user_role");
                });

            modelBuilder.Entity("A0009_EF_Postgres_V8.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Dictionary<string, string>>("Translations")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("product");
                });

            modelBuilder.Entity("A0009_EF_Postgres_V8.Model.TestData", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("address");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("phone");

                    b.HasKey("ID");

                    b.ToTable("test_data");
                });

            modelBuilder.Entity("A0009_EF_Postgres_V8.Model.Document", b =>
                {
                    b.HasOne("A0009_EF_Postgres_V8.Model.DocumentType", "DocumentType")
                        .WithMany("DocumentList")
                        .HasForeignKey("DocumentTypeCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentType");
                });

            modelBuilder.Entity("A0009_EF_Postgres_V8.Model.MrUserExp", b =>
                {
                    b.HasOne("A0009_EF_Postgres_V8.Model.MrUser", "User")
                        .WithOne("UserExp")
                        .HasForeignKey("A0009_EF_Postgres_V8.Model.MrUserExp", "UserCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("A0009_EF_Postgres_V8.Model.MrUserRole", b =>
                {
                    b.HasOne("A0009_EF_Postgres_V8.Model.MrRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("A0009_EF_Postgres_V8.Model.MrUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("A0009_EF_Postgres_V8.Model.Product", b =>
                {
                    b.OwnsMany("A0009_EF_Postgres_V8.Model.Review", "Reviews", b1 =>
                        {
                            b1.Property<int>("ProductId")
                                .HasColumnType("integer");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<string>("Content")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("Rating")
                                .HasColumnType("integer");

                            b1.Property<string>("User")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ProductId", "Id");

                            b1.ToTable("product");

                            b1.ToJson("Reviews");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.OwnsOne("A0009_EF_Postgres_V8.Model.Specifications", "Specifications", b1 =>
                        {
                            b1.Property<int>("ProductId")
                                .HasColumnType("integer");

                            b1.Property<string>("Color")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Dimensions")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Material")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ProductId");

                            b1.ToTable("product");

                            b1.ToJson("Specifications");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.Navigation("Reviews");

                    b.Navigation("Specifications")
                        .IsRequired();
                });

            modelBuilder.Entity("A0009_EF_Postgres_V8.Model.DocumentType", b =>
                {
                    b.Navigation("DocumentList");
                });

            modelBuilder.Entity("A0009_EF_Postgres_V8.Model.MrRole", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("A0009_EF_Postgres_V8.Model.MrUser", b =>
                {
                    b.Navigation("UserExp")
                        .IsRequired();

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
