// <auto-generated />
using A0040_React.DataAccess;
using A0040_React.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace A0040_React.Migrations
{
    [DbContext(typeof(MyReportContext))]
    partial class MyReportContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("A0040_React.Model.AutoReportDetail", b =>
                {
                    b.Property<long>("AutoReportDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("auto_report_detail_id");

                    b.Property<long>("AutoReportMasterID")
                        .HasColumnName("auto_report_master_id");

                    b.Property<int>("ReportID")
                        .HasColumnName("report_id");

                    b.Property<string>("ReportParameter")
                        .HasColumnName("report_parameter")
                        .HasMaxLength(512);

                    b.HasKey("AutoReportDetailID");

                    b.HasIndex("AutoReportMasterID");

                    b.HasIndex("ReportID");

                    b.ToTable("auot_report_detail");
                });

            modelBuilder.Entity("A0040_React.Model.AutoReportDetailFile", b =>
                {
                    b.Property<long>("AutoReportDetailFileID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("auto_report_detail_file_id");

                    b.Property<long>("AutoReportDetailID")
                        .HasColumnName("auto_report_detail_id");

                    b.Property<int>("ReportFileFormat")
                        .HasColumnName("auto_report_format");

                    b.Property<string>("ReportFileName")
                        .IsRequired()
                        .HasColumnName("auto_report_file_name")
                        .HasMaxLength(128);

                    b.HasKey("AutoReportDetailFileID");

                    b.HasIndex("AutoReportDetailID");

                    b.ToTable("auot_report_detail_file");
                });

            modelBuilder.Entity("A0040_React.Model.AutoReportMaster", b =>
                {
                    b.Property<long>("AutoReportMasterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("auto_report_master_id");

                    b.Property<int>("AutoReportDays")
                        .HasColumnName("auto_report_days");

                    b.Property<int>("AutoReportType")
                        .HasColumnName("auto_report_type");

                    b.Property<string>("MailBody")
                        .IsRequired()
                        .HasColumnName("auto_report_mail_body");

                    b.Property<string>("MailSubject")
                        .IsRequired()
                        .HasColumnName("auto_report_mail_subject")
                        .HasMaxLength(256);

                    b.Property<int>("ProcessHourMin")
                        .HasColumnName("auto_report_hour_min");

                    b.Property<string>("ReportMailCC")
                        .HasColumnName("auto_report_mail_cc")
                        .HasMaxLength(512);

                    b.Property<string>("ReportMailTo")
                        .IsRequired()
                        .HasColumnName("auto_report_mail_to")
                        .HasMaxLength(512);

                    b.HasKey("AutoReportMasterID");

                    b.ToTable("auot_report_master");
                });

            modelBuilder.Entity("A0040_React.Model.Report", b =>
                {
                    b.Property<int>("ReportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("report_id");

                    b.Property<string>("ReportFileName")
                        .IsRequired()
                        .HasColumnName("report_file_name")
                        .HasMaxLength(64);

                    b.Property<string>("ReportName")
                        .IsRequired()
                        .HasColumnName("report_name")
                        .HasMaxLength(64);

                    b.HasKey("ReportID");

                    b.ToTable("cr_report");
                });

            modelBuilder.Entity("A0040_React.Model.AutoReportDetail", b =>
                {
                    b.HasOne("A0040_React.Model.AutoReportMaster", "AutoReportMasterData")
                        .WithMany("AutoReportDetailList")
                        .HasForeignKey("AutoReportMasterID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("A0040_React.Model.Report", "ReportData")
                        .WithMany("AutoReportDetailList")
                        .HasForeignKey("ReportID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("A0040_React.Model.AutoReportDetailFile", b =>
                {
                    b.HasOne("A0040_React.Model.AutoReportDetail", "AutoReportDetailData")
                        .WithMany("AutoReportDetailFileList")
                        .HasForeignKey("AutoReportDetailID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
