// <auto-generated />
using System;
using D0010_MyTodo.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace D0010_MyTodo.Migrations
{
    [DbContext(typeof(MyTodoContext))]
    partial class MyTodoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("D0010_MyTodo.Model.Todo", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ClosingDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("closing_date");

                    b.Property<string>("Detail")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasColumnName("detail");

                    b.Property<byte>("Importance")
                        .HasColumnType("INTEGER")
                        .HasColumnName("importance");

                    b.Property<bool>("IsDone")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_done");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.HasKey("ID");

                    b.ToTable("my_todo_list");
                });
#pragma warning restore 612, 618
        }
    }
}
