// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using P0002_MyTrading.DataAccess;

namespace P0002_MyTrading.Migrations
{
    [DbContext(typeof(MyTradingContext))]
    partial class MyTradingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("P0002_MyTrading.Model.SimpleTrading", b =>
                {
                    b.Property<long>("TradingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("trading_id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime?>("CloseDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("close_date");

                    b.Property<decimal?>("ClosePrice")
                        .HasColumnType("numeric")
                        .HasColumnName("close_price");

                    b.Property<DateTime>("OpenDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("open_date");

                    b.Property<decimal>("OpenPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("open_price");

                    b.Property<string>("TradingItemCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("trading_item_code");

                    b.Property<int>("TradingQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("trading_quantity");

                    b.HasKey("TradingID");

                    b.ToTable("simple_trading", "my_trading");
                });
#pragma warning restore 612, 618
        }
    }
}
